// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rozpewnnkvhxalqhipsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvenBld25ua3ZoeGFscWhpcHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzg1MjYsImV4cCI6MjA2NTkxNDUyNn0.mwCUAcDN-GO7Chy5VRREG2Ofoe7gIk1xVKM5CILwjrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);